source:
  type: sqlalchemy
  config:
    platform: sqlite
    connect_uri: sqlite:////Users/sanjiuganmaoling/Desktop/code/data-experience/lab/input/demo_metadata.db
    include_tables: true
    include_views: true
    profiling:
      enabled: false
sink:
  type: datahub-rest
  config:
    server: http://localhost:8080
